### ISSUE TITLE
Add SnpEff for annotation of snp variants

### ISSUE THREAD

**Issue by DrB-S** [UPHL-BioNGS/Grandeur#105]
SnpEff (https://pcingola.github.io/SnpEff/#snpeff) annotates functions of snp variants.  SnpEff requires input vcf files, which require bam file input. Complicated! It doesn't appear that any of Grandeur's modules produce bam or vcf files, however....

**Comment by erinyoung** [comment]
I think would be useful.

Since there's no reference for the input files, there's nothing to align reads to, so there's no vcf, gff, or gbk files. SnpEff has nothing to work on.

Right now, Grandeur uses prokka for an on-the-fly genome annotation, and then roary for core genome alignment. I think this is fine for most things, but roary is no longer supported, and it's likely time to move on. I've thought about working on updating the multiple sequence alignment workflow, but then I've also heard rumors of others creating similar workflows and I don't want to steal their thunder.

I was looking at the [HarvestTools suite](https://harvest.readthedocs.io/en/latest/content/harvest/quickstart.html), but maybe there's already a workflow that exists that would be better for your needs (I haven't tried using [nf-core's pangenome workflow](https://nf-co.re/pangenome/1.0.0))
